# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdff2d24610a24c5a3ddc1c81bff2f5aa24218bb225d5d6cae3ad208ea85156f54576e6943479c6e32011988d4281362ab8f9f0321d7680263ade1bf4ccdf5fe

test:
  secret_key_base: 960e010b0ced1935dbf2311436d07cd03138a89d912e39a9eff5bf2b4ba8413b98bbd912093e890e648b19d064c5bd8ad713c83614408b5ea02fe44577510422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
